// ============================================
// ENUMS
// ============================================

export enum UserRole {
  CLIENT = "CLIENT",
  PROFESSIONAL = "PROFESSIONAL",
  COMPANY = "COMPANY",
  ADMIN = "ADMIN",
}

export enum UserStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  INACTIVE = "INACTIVE",
}

export enum ServiceOrderStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  IN_PROGRESS = "IN_PROGRESS",
  AWAITING_CLIENT_CONFIRMATION = "AWAITING_CLIENT_CONFIRMATION",
  AWAITING_PROFESSIONAL_CONFIRMATION = "AWAITING_PROFESSIONAL_CONFIRMATION",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  DISPUTED = "DISPUTED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  HELD = "HELD",
  RELEASED = "RELEASED",
  REFUNDED = "REFUNDED",
  FAILED = "FAILED",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
}

export enum NotificationType {
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_ACCEPTED = "ORDER_ACCEPTED",
  ORDER_COMPLETED = "ORDER_COMPLETED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  PAYMENT_RELEASED = "PAYMENT_RELEASED",
  DEADLINE_WARNING = "DEADLINE_WARNING",
  DEADLINE_EXPIRED = "DEADLINE_EXPIRED",
  NEW_MESSAGE = "NEW_MESSAGE",
  REVIEW_RECEIVED = "REVIEW_RECEIVED",
  SYSTEM_ALERT = "SYSTEM_ALERT",
  PROFESSIONAL_EN_ROUTE = "PROFESSIONAL_EN_ROUTE",
}

export enum NotificationStatus {
  UNREAD = "UNREAD",
  READ = "READ",
  ARCHIVED = "ARCHIVED",
}

export enum ServiceCategoryType {
  HOME_SERVICES = "HOME_SERVICES",
  BUSINESS_SERVICES = "BUSINESS_SERVICES",
  BOTH = "BOTH",
}

export enum VerificationType {
  DOCUMENT = "DOCUMENT",
  FACIAL = "FACIAL",
}

export enum VerificationSubmissionStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum SalaryStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
}
